
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://vocaluxe.org"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

repository: Vocaluxe/Vocaluxe

#####################
# HTML Head and SEO #
#####################

lang: "en_US"
author: "Vocaluxe Team"
title: "Vocaluxe"
subtitle: "Sing your favorite songs"
description: "Vocaluxe is a free and open source singing game, inspired by SingStar™ and the great Ultrastar Deluxe project for up to six players."
full-description: "Vocaluxe is a free and open source singing game, inspired by SingStar™ and the great Ultrastar Deluxe project. It allows up to six players to sing along with music using microphones in order to score points, depending on the pitch of the voice and the rhythm of singing."
keywords: "Vocaluxe, SingStar, UltraStar, sing, singen, game, party, karaoke, song, Lied, singing, open source, free, gratis, multiplayer, pc, computer, download"
favicon: "/img/vocaluxe_icon.png"
logo: "/img/vocaluxe_icon.png"

social:
  name: Vocaluxe
  links:
    - https://www.facebook.com/Vocaluxe
    - https://github.com/Vocaluxe/Vocaluxe

################
# Header layout #
################

faviconPng: "/img/vocaluxe_icon.png"

##############################
# Color the browser elements #
##############################
color-browser: "#2C3E50"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

########
# Blog #
########

post-preview-words: 80
big-post-preview-words: 200
excerpt_separator: <!--more-->

paginate: 5

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Home: 'hero-area'
  News: 'news'
  Download: 'download'
  Features: 'about'
  Help: 'help'
  Contribute: 'contribute'
  Songs: 'songs'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "/blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - github-pages
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  #- jemoji
